environment:
  name: dev

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        boot:
          autoconfigure:
            flyway: DEBUG
        security: DEBUG

spring:
  lifecycle: 
    timeout-per-shutdown-phase: 30s
  
  datasource:
    # Let op: Je Docker draait op 5433, dus gebruik hier ook 5433!
    url: jdbc:postgresql://localhost:5432/FormBuilderDB 
    username: formbuilder
    password: 13Et1lXt12231lLUft1aAeQpF4
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  messages:
    basename: i18n/errors,i18n/admin
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  forward-headers-strategy: native
  shutdown: graceful

file:
  storage:
    path: forms

app:
  admin:
    username: ${ADMIN_USER:admin}
    email: ${ADMIN_EMAIL:admin@admin.com}
    password: ${ADMIN_PASS:admin123}
