environment:
  name: test

server:
  forward-headers-strategy: native
  shutdown: graceful

spring:
  profiles:
    active:
    - test

  lifecycle: 
    timeout-per-shutdown-phase: 30s


file:
  storage:
    path: forms